CREATE TABLE IF NOT EXISTS public."FIN_BillingItem"
(
    "Id" uuid NOT NULL,
    "BillingId" uuid NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Amount" numeric NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "Quantity" integer NOT NULL,
    "StudentName" text COLLATE pg_catalog."default",
    "StudentId" text COLLATE pg_catalog."default",
    "NRIC" text COLLATE pg_catalog."default",
    "CitizenshipType" integer NOT NULL,
    "UserProfileId" uuid,
    "Group" integer,
    "FullAmount" numeric,
    "Type" integer NOT NULL,
    "Index" integer NOT NULL,
    "Remarks" text COLLATE pg_catalog."default",
    "TotalHours" double precision NOT NULL,
    "PDCHours" double precision NOT NULL,
    "TierName" text COLLATE pg_catalog."default",
    "Extension" jsonb,
    "ItemReference" jsonb,
    "TierReference" jsonb,
    "IHLFlag" integer NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" uuid NOT NULL,
    "LegacyDataExtension" jsonb,
    CONSTRAINT "PK_FIN_BillingItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FIN_BillingItem_FIN_Billing_BillingId" FOREIGN KEY ("BillingId")
        REFERENCES public."FIN_Billing" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)



CREATE TABLE IF NOT EXISTS public."FIN_Billing"
(
    "Id" uuid NOT NULL,
    "RequestId" uuid,
    "OldRequestId" uuid,
    "IsTransfer" boolean,
    "ApplicationId" text COLLATE pg_catalog."default",
    "EnrollmentStatus" integer,
    "WithdrawReason" integer,
    "WithdrawReasonId" uuid,
    "ApplicationStatus" integer,
    "SemesterId" uuid,
    "AcadYear" text COLLATE pg_catalog."default",
    "SemesterCode" text COLLATE pg_catalog."default",
    "CourseIntakeId" uuid,
    "CourseIntakePaymentOption" integer NOT NULL,
    "CourseId" uuid,
    "CourseVersion" integer NOT NULL,
    "CourseVersionId" uuid,
    "CourseTypeId" uuid,
    "CourseTypeName" text COLLATE pg_catalog."default",
    "CourseCategoryId" uuid,
    "CourseCategoryName" text COLLATE pg_catalog."default",
    "CourseCode" text COLLATE pg_catalog."default",
    "CourseIntakeName" text COLLATE pg_catalog."default",
    "CourseIntakeNumber" text COLLATE pg_catalog."default",
    "CourseSemesterStartDate" timestamp with time zone,
    "CourseSemesterEndDate" timestamp with time zone,
    "CourseIntakeOpenToType" integer,
    "BillingBy" integer,
    "IHLCourseTypeId" uuid,
    "CatalogueId" uuid,
    "AttendancePercentage" numeric NOT NULL,
    "DebtorType" integer,
    "UserProfileId" uuid,
    "DebtorName" text COLLATE pg_catalog."default",
    "DebtorInfo" jsonb,
    "StudentId" text COLLATE pg_catalog."default",
    "NRIC" text COLLATE pg_catalog."default",
    "Address" jsonb,
    "PaymentMode" jsonb,
    "BillingFor" integer,
    "BillingNumber" text COLLATE pg_catalog."default",
    "InvoiceIssuedDate" timestamp with time zone,
    "BillingStatus" integer,
    "BillingConfirmDate" timestamp with time zone,
    "TermVersionId" uuid,
    "TermNumber" numeric,
    "TermUnit" integer,
    "PaymentAndCreditTerm" text COLLATE pg_catalog."default",
    "PaymentDueDate" timestamp with time zone,
    "Source" integer,
    "PaymentStatus" integer,
    "SFCStatus" integer,
    "PSEAStatus" integer,
    "GIROStatus" integer,
    "OtherPaymentStatus" integer,
    "InvoiceAmount" numeric,
    "DeemedPaidAmount" numeric,
    "OutstandingAmount" numeric,
    "PaidAmount" numeric,
    "OddCentAmount" numeric,
    "ExcessAmount" numeric,
    "OffsetAmount" numeric,
    "InstalmentAmount" numeric,
    "CompanySponsorAmount" numeric,
    "IsInternalCharging" boolean,
    "InstalmentPlanId" uuid,
    "InstalmentIsOpen" boolean,
    "InstalmentPlanStatus" integer,
    "ExternalRemarks" text COLLATE pg_catalog."default",
    "CompanyId" uuid,
    "CompanyBillingId" uuid,
    "IsTier" boolean,
    "UEN" text COLLATE pg_catalog."default",
    "BusinessUnitCodeId" uuid,
    "SubBusinessUnit" text COLLATE pg_catalog."default",
    "PONumber" text COLLATE pg_catalog."default",
    "OwnerId" uuid,
    "CompanyBillingContactUserId" uuid,
    "CompanyBranchId" uuid,
    "CompanyBranchName" text COLLATE pg_catalog."default",
    "ContactPersonName" text COLLATE pg_catalog."default",
    "ContactPersonEmail" text COLLATE pg_catalog."default",
    "ContactPersonPhone" text COLLATE pg_catalog."default",
    "InvoiceIssuedDueDate" timestamp with time zone,
    "OnlineCourseBiunique" boolean,
    "CompanyCategory" integer NOT NULL,
    "AGDIsPreferred" integer NOT NULL,
    "PreferredPlatform" text COLLATE pg_catalog."default",
    "AGDEInvoiceDate" timestamp with time zone,
    "SentToAGD" integer NOT NULL,
    "SentToAGDDate" timestamp with time zone,
    "SentToOtherPlatformDate" timestamp with time zone,
    "TGSNumber" text COLLATE pg_catalog."default",
    "InvoiceNumber" text COLLATE pg_catalog."default",
    "CreditNoteId" uuid,
    "CreditNoteNumber" text COLLATE pg_catalog."default",
    "CreditNoteStatus" integer,
    "CreditNoteAmount" numeric,
    "CreditNoteDate" timestamp with time zone,
    "NewTaxInvoiceNumber" text COLLATE pg_catalog."default",
    "NewTaxInvoiceDate" timestamp with time zone,
    "ProceedPayment" boolean NOT NULL,
    "BillingType" integer NOT NULL,
    "NewBillingId" uuid,
    "OldBillingId" uuid,
    "OldBillingNumber" text COLLATE pg_catalog."default",
    "SentLetterCount" integer NOT NULL,
    "StudentTaskId" uuid,
    "FeeAdjustmentStudentTaskId" uuid,
    "StudentRequestNumber" text COLLATE pg_catalog."default",
    "WorkflowId" uuid,
    "WorkflowStatus" integer NOT NULL,
    "WorkflowType" integer NOT NULL,
    "OfficialReason" text COLLATE pg_catalog."default",
    "Remarks" text COLLATE pg_catalog."default",
    "HisRefundAmount" numeric,
    "AccountingStatus" integer,
    "ReminderRuleSendEmailList" jsonb,
    "MECTModuleIds" jsonb,
    "IsUsedClaimItem" boolean NOT NULL,
    "IsWriteOff" integer NOT NULL,
    "FQFundingType" integer,
    "Extension" jsonb,
    "Documents" jsonb,
    "InvoiceFileName" text COLLATE pg_catalog."default",
    "InvoiceFilePath" text COLLATE pg_catalog."default",
    "WorkTagTemplateItems" jsonb,
    "IsMOE" boolean,
    "CompanyRelatedPartyWorktagCode" text COLLATE pg_catalog."default",
    "SearchText" text COLLATE pg_catalog."default",
    "IHLFlag" integer NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" uuid NOT NULL,
    "LegacyDataExtension" jsonb,
    CONSTRAINT "PK_FIN_Billing" PRIMARY KEY ("Id")
)